<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="admin" name="Test-Firefox-Runner" tests="8" failures="1" timestamp="2 Mar 2021 02:13:31 GMT" time="452.04" errors="0">
  <testcase name="ValidateCopyShippingAddressRadiobutton" time="28.229" classname="Organization.ValidateCSARadioBtn"/>
  <testcase name="RatingDropdown" time="27.153" classname="Organization.ValidateRatingDropdown"/>
  <testcase name="NotifyOwnerChechboxvalidation" time="26.504" classname="Organization.ValidateNOCkeckBox"/>
  <testcase name="ValidateCopyBillingAddressRadiobutton" time="28.688" classname="Organization.ValidateCBARadioBtn"/>
  <testcase name="createWithNotifyOwner" time="40.243" classname="Organization.createOrgWithNotifyOwner">
    <skipped/>
  </testcase> <!-- createWithNotifyOwner -->
  <testcase name="createWithNotifyOwner" time="30.541" classname="Organization.createOrgWithNotifyOwner">
    <skipped/>
  </testcase> <!-- createWithNotifyOwner -->
  <testcase name="createWithNotifyOwner" time="31.563" classname="Organization.createOrgWithNotifyOwner">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at Organization.createOrgWithNotifyOwner.createWithNotifyOwner(createOrgWithNotifyOwner.java:53)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- createWithNotifyOwner -->
  <testcase name="createWithRating" time="37.835" classname="Organization.createOrgWithRating"/>
</testsuite> <!-- Test-Firefox-Runner -->
