<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="admin" name="Test-Chrome-Runner" tests="8" failures="1" timestamp="2 Mar 2021 02:13:48 GMT" time="468.938" errors="0">
  <testcase name="ValidateCopyShippingAddressRadiobutton" time="27.722" classname="Organization.ValidateCSARadioBtn"/>
  <testcase name="RatingDropdown" time="26.82" classname="Organization.ValidateRatingDropdown"/>
  <testcase name="NotifyOwnerChechboxvalidation" time="26.207" classname="Organization.ValidateNOCkeckBox"/>
  <testcase name="ValidateCopyBillingAddressRadiobutton" time="23.384" classname="Organization.ValidateCBARadioBtn"/>
  <testcase name="createWithNotifyOwner" time="39.446" classname="Organization.createOrgWithNotifyOwner">
    <skipped/>
  </testcase> <!-- createWithNotifyOwner -->
  <testcase name="createWithNotifyOwner" time="33.054" classname="Organization.createOrgWithNotifyOwner">
    <skipped/>
  </testcase> <!-- createWithNotifyOwner -->
  <testcase name="createWithNotifyOwner" time="40.426" classname="Organization.createOrgWithNotifyOwner">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at Organization.createOrgWithNotifyOwner.createWithNotifyOwner(createOrgWithNotifyOwner.java:53)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- createWithNotifyOwner -->
  <testcase name="createWithRating" time="35.456" classname="Organization.createOrgWithRating"/>
</testsuite> <!-- Test-Chrome-Runner -->
